[package]
name = "icon-cutter"
version = "0.1.6"
authors = ["L <rohesie@gmail.com>"]
edition = "2018"
license = "AGPL"
description = "icon-cutter is a library which creates .dmi files tailored to use with an 8-bit bitmasking system for smooth icons in in the DM game programming language."
homepage = "https://github.com/tgstation/icon-cutter"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dmi = { git = "https://github.com/spacestation13/dmi", tag = "v0.3.5" }
anyhow = "1.0"
image = { version = "0.25.1", default-features = false, features = ["rayon", "png"] }
yaml-rust2 = "0.8.1"
dont_disappear = "3.0"
