## Uncomment by removing the '#' character in front of them to enable these ##
#output_name: "output"
#base_icon_state: "icon"

north_end: 6

se_convex: 0
nw_convex: 0
ne_convex: 0
sw_convex: 0

se_concave: 1
nw_concave: 1
ne_concave: 1
sw_concave: 1

se_horizontal: 2
nw_horizontal: 2
ne_horizontal: 2
sw_horizontal: 2

se_vertical: 3
nw_vertical: 3
ne_vertical: 3
sw_vertical: 3
