## Uncomment by removing the '#' character in front of them to enable these ##
#output_name: "output"
#base_icon_state: "icon"

se_convex: 0
nw_convex: 0
ne_convex: 0
sw_convex: 0

se_vertical: 1
nw_vertical: 1
ne_vertical: 1
sw_vertical: 1

se_horizontal: 2
nw_horizontal: 2
ne_horizontal: 2
sw_horizontal: 2

se_concave: 3
nw_concave: 3
ne_concave: 3
sw_concave: 3

se_flat: 4
nw_flat: 4
ne_flat: 4
sw_flat: 4
